name: MolDA_CHJ
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - comm=0.2.3=py310h06a4308_0
  - decorator=5.2.1=py310h06a4308_0
  - executing=2.2.1=py310h06a4308_0
  - expat=2.7.3=h7354ed3_1
  - jedi=0.19.2=py310h06a4308_0
  - jupyter_client=8.6.3=py310h06a4308_1
  - jupyter_core=5.9.1=py310h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libsodium=1.0.20=heac8642_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - matplotlib-inline=0.2.1=py310h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=py310h06a4308_1
  - parso=0.8.5=py310h06a4308_0
  - pexpect=4.9.0=py310h06a4308_1
  - pip=25.3=pyhc872135_0
  - prompt-toolkit=3.0.52=py310h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py310h06a4308_0
  - pygments=2.19.2=py310h06a4308_0
  - python=3.10.19=h6fa692b_0
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - pyzmq=27.1.0=py310hcf8288c_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=py310h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - traitlets=5.14.3=py310h06a4308_0
  - typing-extensions=4.15.0=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==0.24.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - altair==6.0.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - bert-score==0.3.13
      - bleach==6.3.0
      - blinker==1.9.0
      - blis==1.3.3
      - braceexpand==0.1.7
      - cachetools==6.2.2
      - catalogue==2.0.10
      - certifi==2025.11.12
      - cffi==2.0.0
      - cfgv==3.5.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpathlib==0.23.0
      - confection==0.1.5
      - contexttimer==0.3.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - cymem==2.0.13
      - datasets==2.19.1
      - debugpy==1.8.17
      - decord==0.6.0
      - deepchem==2.8.0
      - deepspeed==0.18.2
      - defusedxml==0.7.1
      - dill==0.3.7
      - distlib==0.4.0
      - distro==1.9.0
      - einops==0.8.1
      - evaluate==0.4.6
      - exceptiongroup==1.3.1
      - fairscale==0.4.4
      - fancycompleter==0.11.1
      - fastjsonschema==2.21.2
      - fcd==1.2.2
      - filelock==3.19.1
      - flash-attn==2.8.3
      - fonttools==4.61.0
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2023.6.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.23.5
      - hydra-core==1.3.2
      - identify==2.6.15
      - idna==3.11
      - imageio==2.37.2
      - iopath==0.1.10
      - ipykernel==7.1.0
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kaggle==1.7.4.5
      - kiwisolver==1.4.9
      - lark==1.3.1
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - littleutils==0.2.4
      - markdown==3.10
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mistune==3.1.4
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.15
      - murmurhash==1.0.15
      - narwhals==2.13.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.3
      - ninja==1.13.0
      - nltk==3.9.2
      - nodeenv==1.9.1
      - notebook==7.5.0
      - notebook-shim==0.2.4
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - ogb==1.3.6
      - omegaconf==2.3.0
      - openai==2.14.0
      - opencv-python-headless==4.5.5.64
      - opendatasets==0.1.22
      - outdated==0.2.2
      - overrides==7.7.0
      - pandarallel==1.6.5
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - pdbpp==0.11.7
      - peft==0.12.0
      - pillow==11.3.0
      - platformdirs==4.5.1
      - plotly==6.5.0
      - portalocker==3.2.0
      - pre-commit==4.5.0
      - preshed==3.0.12
      - prometheus-client==0.23.1
      - propcache==0.4.1
      - protobuf==3.20.3
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pyarrow-hotfix==0.7
      - pycocoevalcap==1.2
      - pycocotools==2.0.10
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydeck==0.9.1
      - pynvml==13.0.1
      - pyparsing==3.2.5
      - pyrepl==0.11.4
      - python-json-logger==4.0.0
      - python-levenshtein==0.12.2
      - python-magic==0.4.27
      - python-slugify==8.0.4
      - pytorch-lightning==2.6.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - rdkit==2025.9.3
      - rdkit-pypi==2022.9.5
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rouge==1.0.1
      - rouge-score==0.1.2
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - salesforce-lavis==1.0.0
      - schedule==1.2.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - selfies==2.2.0
      - send2trash==1.8.3
      - sentencepiece==0.2.1
      - sentry-sdk==2.47.0
      - shellingham==1.5.4
      - smart-open==7.5.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - spacy==3.8.11
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.2
      - streamlit==1.52.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - text-unidecode==1.3
      - thinc==8.3.10
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==0.4.12
      - tinycss2==1.4.0
      - tokenizers==0.19.1
      - toml==0.10.2
      - tomli==2.3.0
      - torch==2.5.1+cu121
      - torch-geometric==2.7.0
      - torchaudio==2.5.1+cu121
      - torchmetrics==1.8.2
      - torchvision==0.20.1+cu121
      - tornado==6.5.2
      - tqdm==4.67.1
      - transformers==4.44.2
      - triton==3.1.0
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - virtualenv==20.35.4
      - wandb==0.23.1
      - wasabi==1.1.3
      - watchdog==6.0.0
      - wcwidth==0.2.14
      - weasel==0.4.3
      - webcolors==25.10.0
      - webdataset==1.0.2
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.4
      - widgetsnbextension==4.0.15
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /home/jovyan/miniconda3/envs/MolDA_CHJ
