gnn_type: gine_tokengt
gnn_hidden_dim: 1024
gine:
  gnn_hidden_dim: 1024
  gin_num_layers: 5
  drop_ratio: 0.0
  used_gnn_layer: -1
  gnn_jk: last
  graph_encoder_ckpt: /app/Mol-LLM/checkpoint/mol-llm.ckpt
  gnn_type: gine
tokengt:
  input_feat_dim: 9
  gnn_hidden_dim: 1024
  num_layers: 5
  num_heads: 8
  method: laplacian
  d_p: 64
  d_e: 64
  use_graph_token: True
  max_position_embeddings: 102
  graph_encoder_ckpt: /app/Mol-LLM/checkpoint/mol-llm.ckpt
  gnn_type: tokengt