raw_data_root: Mol-LLM_Custom/dataset/real_train
data_tag: 3.3M_0415

target_benchmarks:
  # - alchemy_homo
  # - alchemy_homo_lumo_gap
  # - alchemy_lumo
  # - aqsol-logS
  # - bace
  # - chebi-20-mol2text
  # - chebi-20-text2mol
  # - forward_reaction_prediction
  # - orderly-forward_reaction_prediction
  # - orderly-retrosynthesis
  # - presto-forward_reaction_prediction
  # - presto-retrosynthesis
  # - qm9_homo
  # - qm9_homo_lumo_gap
  # - qm9_lumo
  # - reagent_prediction
  # - retrosynthesis
  # - smol-forward_synthesis
  # - smol-molecule_captioning
  # - smol-molecule_generation
  # - smol-property_prediction-bbbp
  # - smol-property_prediction-clintox
  # - smol-property_prediction-esol
  # - smol-property_prediction-hiv
  # - smol-property_prediction-lipo
  # - smol-property_prediction-sider
  # - smol-retrosynthesis
  # - smol-name_conversion-i2s
  # - smol-name_conversion-s2i
  - bace
  # - chebi-20-mol2text
  # - chebi-20-text2mol
  # - forward_reaction_prediction
  # - qm9_homo
  # - qm9_homo_lumo_gap
  # - qm9_lumo
  # - reagent_prediction
  # - retrosynthesis
  # - smol-forward_synthesis
  # - smol-molecule_captioning
  # - smol-molecule_generation
  # - smol-property_prediction-bbbp
  # - smol-property_prediction-clintox
  # - smol-property_prediction-esol
  # - smol-property_prediction-hiv
  # - smol-property_prediction-lipo
  # - smol-property_prediction-sider
  # - smol-retrosynthesis
  # # - smol-name_conversion-i2f
  # - smol-name_conversion-i2s
  # # - smol-name_conversion-s2f
  # - smol-name_conversion-s2i