defaults:
  - data: test_CHJ
  - gnn: gine_tokengt
  - trainer: mistral7b_80gb

# General settings
filename: debugging
seed: 42
mode: ft

wandb_entity: hj_ai
wandb_project: mol-llm
wandb_log_freq: 100
wandb_id: null

debug: false
ckpt_path: null
pretrained_ckpt_path: null

shuffle_selfies: false
shuffle_graph: false
process_disjoint: true