defaults:
  - data: multi_task_stage1
  - gnn: gine_tokengt
  - trainer: mistral7b_80gb

# General settings
filename: mol_llada_lora_run
seed: 42
mode: ft

wandb_entity: hj_ai
wandb_project: mol-llm_llada
wandb_log_freq: 100
wandb_id: null

custom_log: True
debug: false
ckpt_path: null
pretrained_ckpt_path: null

shuffle_selfies: false
shuffle_graph: false
process_disjoint: true